---
AWSTemplateFormatVersion: '2010-09-09'

Description: "Creates an s3 static website bucket for a given 'RootDomainName'"

Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String

Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - www.${Domain}
        - Domain: !Ref RootDomainName
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  RootBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${RootBucket.Arn}/*'
            # CF Distribution ARNs have to be manually constructed
            Condition:
              StringLike:
                AWS:Referer:
                  - !Sub
                    - ${Domain}/*
                    - Domain: !Ref RootDomainName
                  - !Sub
                    - www.${Domain}/*
                    - Domain: !Ref RootDomainName

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
