service: dgnx-website
frameworkVersion: '2 || 3'

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-api-cloudfront

custom:
  corsAllowedOrigin:
    dev: http://localhost:3000
    staging: http://staging.dgnx.finance.s3-website-eu-west-1.amazonaws.com
    production: https://www.dgnx.finance

provider:
  name: aws
  region: eu-west-1
  profile: dgnx
  stage: dev
  runtime: nodejs18.x

  environment:
    CORS_ALLOWED_ORIGIN: ${self:custom.corsAllowedOrigin.${opt:stage, self:provider.stage}}

functions:
  snowtraceProxy:
    handler: snowtraceProxy/get.handler
    memorySize: 512
    timeout: 29
    events:
      - http:
          cors: true
          path: /snowtrace
          method: get
